package com.dbc.enums;

import com.fasterxml.jackson.annotation.JsonValue;

public enum Tipo {
    NORMAL(1, "NORMAL", "", "PEDRA,FANTASMA,AÇO", "FANTASMA", "LUTADOR"),
    LUTADOR(2, "LUTADOR", "NORMAL,PEDRA,AÇO,GELO,ESCURIDÃO", "VOADOR,VENENOSO,PSÍQUICO,INSETO,FANTASMA,FADA", "PEDRA,INSETO,ESCURIDÃO", "VOADOR,PSÍQUICO,FADA"),
    VOADOR(3, "VOADOR", "LUTADOR,INSETO,PLANTA", "PEDRA,AÇO,ELÉTRICO", "LUTADOR,TERRA,INSETO,PLANTA", "PEDRA,ELÉTRICO,GELO"),
    VENENOSO(4, "VENENOSO", "PLANTA,FADA", "VENENOSO,TERRA,PEDRA,FANTASMA,AÇO", "LUTADOR,VENENOSO,PLANTA,FADA", "TERRA,PSÍQUICO"),
    TERRA(5, "TERRA", "VENENOSO,PEDRA,AÇO,FOGO,ELÉTRICO", "VOADOR,INSETO,PLANTA", "VENENOSO,PEDRA,ELÉTRICO", "ÁGUA,PLANTA,GELO"),
    PEDRA(6, "PEDRA", "VOADOR,INSETO,FOGO,GELO", "LUTADOR,TERRA,AÇO", "NORMAL,VOADOR,VENENOSO,FOGO", "LUTADOR,TERRA,AÇO,ÁGUA,PLANTA"),
    INSETO(7, "INSETO", "PLANTA,PSÍQUICO,ESCURIDÃO", "LUTADOR,VOADOR,VENENOSO,FANTASMA,AÇO,FOGO,FADA", "LUTADOR,TERRA,PLANTA", "VOADOR,PEDRA,FOGO"),
    FANTASMA(8, "FANTASMA", "FANTASMA,PSÍQUICO", "NORMAL,ESCURIDÃO", "NORMAL,LUTADOR,VENENOSO,INSETO", "FANTASMA,ESCURIDÃO"),
    ACO(9, "AÇO", "PEDRA,GELO,FADA", "AÇO,FOGO,ÁGUA,ELÉTRICO", "NORMAL,VOADOR,VENENOSO,PEDRA,INSETO,AÇO,PLANTA,PSÍQUICO,GELO,DRAGÃO,FADA", "LUTADOR,TERRA,FOGO"),
    FOGO(10, "FOGO", "INSETO,AÇO,PLANTA,GELO", "PEDRA,FOGO,ÁGUA,DRAGÃO", "INSETO,AÇO,FOGO,PLANTA,GELO", "TERRA,PEDRA,ÁGUA"),
    AGUA(11, "ÁGUA", "TERRA,PEDRA,FOGO", "ÁGUA,PLANTA,DRAGÃO", "AÇO,FOGO,ÁGUA,GELO", "PLANTA,ELÉTRICO"),
    PLANTA(12, "PLANTA", "TERRA,PEDRA,ÁGUA", "VOADOR,VENENOSO,INSETO,AÇO,FOGO,PLANTA,DRAGÃO", "TERRA,ÁGUA,PLANTA,ELÉTRICO", "VOADOR,VENENOSO,INSETO,FOGO,GELO"),
    ELETRICO(13, "ELÉTRICO", "VOADOR,ÁGUA", "TERRA,PLANTA,ELÉTRICO,DRAGÃO", "VOADOR,AÇO,ELÉTRICO", "TERRA"),
    PSIQUICO(14, "PSÍQUICO", "LUTADOR,VENENOSO", "AÇO,PSÍQUICO,ESCURIDÃO", "LUTADOR,PSÍQUICO", "INSETO,FANTASMA,ESCURIDÃO"),
    GELO(15, "GELO", "VOADOR,TERRA,PLANTA,DRAGÃO", "AÇO,FOGO,ÁGUA,GELO", "GELO", "LUTADOR,PEDRA,AÇO,FOGO"),
    DRAGAO(16, "DRAGÃO", "DRAGÃO", "AÇO,FADA", "FOGO,ÁGUA,PLANTA,ELÉTRICO", "GELO,DRAGÃO,FADA"),
    FADA(17, "FADA", "LUTADOR,DRAGÃO,ESCURIDÃO", "VENENOSO,AÇO,FOGO", "LUTADOR,INSETO,DRAGÃO,ESCURIDÃO", "VENENOSO,AÇO"),
    ESCURIDAO(18, "ESCURIDÃO", "FANTASMA,PSÍQUICO", "LUTADOR,ESCURIDÃO,FADA", "FANTASMA,PSÍQUICO,ESCURIDÃO", "LUTADOR,INSETO,FADA");

    private Integer id;
    private String nome;
    private String forteContra;
    private String fracoContra;
    private String resistenteA;
    private String vulneravelA;

    Tipo(Integer id, String nome, String forteContra, String fracoContra, String resistenteA, String vulneravelA) {
        this.id = id;
        this.nome = nome;
        this.forteContra = forteContra;
        this.fracoContra = fracoContra;
        this.resistenteA = resistenteA;
        this.vulneravelA = vulneravelA;
    }
}
